version: '3.9'

services:
    mariadb:
        container_name: cy_crypto_mariadb
        image: mariadb:10.10.1-rc
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_USER: cytech
            MYSQL_PASSWORD: cytechpassword
            MYSQL_DATABASE: cycrypto
        networks:
            - database
            - cy_crypto

    adminer:
        container_name: cy_crypto_adminer
        image: adminer:4.8.1
        restart: always
        ports:
            - "2580:8080"
        volumes:
            - ./adminer/adminer.css:/var/www/html/adminer.css:ro
        networks:
            - database

    cy_crypto:
        container_name: cy_crypto_website
        build: ./cy_crypto
        restart: always
        ports:
            - "2480:8080"
        networks:
            - cy_crypto
        command: mvn spring-boot:run

networks:
    cy_crypto:
        driver: bridge
    database:
        driver: bridge