version: '3.9'

services:
    mariadb:
        container_name: jee_project_mariadb
        image: mariadb:10.10.1-rc
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: example
        networks:
            - database
            - jee_website_project

    adminer:
        container_name: jee_project_adminer
        image: adminer:4.8.1
        restart: always
        ports:
            - "8080:2580"
        volumes:
            - ./docker/adminer/adminer.css:/var/www/html/adminer.css:ro
        environment:
            - ADMIN_DEFAULT_SERVER=mariadb
        networks:
            - database

    jee_project:
        container_name: jee_project
        build: ./jee_website_project
        restart: always
        ports:
            - "8080:2480"
        networks:
            - jee_website_project

networks:
    jee_website_project:
        driver: bridge
    database:
        driver: bridge