version: '3.9'

services:
    mariadb:
        container_name: jee_project_mariadb
        image: mariadb:10.10.1-rc
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: example
        networks:
            - backend

    adminer:
        container_name: jee_project_adminer
        image: adminer:4.8.1
        restart: always
        ports:
            - "8080:2580"
        volumes:
            - ./docker/adminer/adminer.css:/var/www/html/adminer.css:ro
        environment:
            - ADMIN_DEFAULT_SERVER=mariadb
        networks:
            - backend

    # jee_project:
    #     container_name: jee_project
    #     build: 
    #         context: .
    #         dockerfile: jee_project.Dockerfile
    #     restart: always
    #     ports:
    #         - "8080:2480"
    #     networks:
    #         - backend

networks:
    backend:
        driver: bridge