spring:
  datasource:
    platform: mariadb
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:42069/cycrypto
    username: cytech
    password: cytechpassword
    initialization-mode: always
  jpa:
    database: MYSQL
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp